-- 물고기 길이가 10cm 이하면 FISH_INFO.LENGTH = NULL
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI 
    JOIN FISH_NAME_INFO FNI
    ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME = 'BASS' OR FNI.FISH_NAME = 'SNAPPER'
    