-- 종류 별 가장 큰 물고기 ID, 이름 FISH_NAME, 길이 LENGTH

SELECT FI.ID AS ID, FNI.FISH_NAME AS FISH_NAME, MF.MAX_LENGTH AS LENGTH
FROM (
    -- 그룹별 제일 긴 애 서브쿼리
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) MF JOIN FISH_NAME_INFO FNI JOIN FISH_INFO FI
    ON MF.FISH_TYPE = FNI.FISH_TYPE AND MF.FISH_TYPE = FI.FISH_TYPE AND FI.LENGTH = MF.MAX_LENGTH
