-- 부서별 평균 연봉 내림차순 정렬
-- 부서 ID : DEPT_ID, 영문 부서명 : DEPT_NAME_EN, 퍙균 연봉(소수점 첫째 자리에 반올림) : AVG_SAL

SELECT 
    HD.DEPT_ID AS DEPT_ID, 
    HD.DEPT_NAME_EN AS DEPT_NAME_EN,
    T.AVG_SAL AS AVG_SAL
FROM (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
    ) T JOIN HR_DEPARTMENT HD
        ON T.DEPT_ID = HD.DEPT_ID
ORDER BY AVG_SAL DESC;
