-- FISH_INFO
-- ID: 물고기 ID, FISH_TYPE: 물고기 종류
-- LENGTH: 물고기 길이 (10cm 이하면 NULL), TIME: 물고기 잡은 날짜

SELECT 
    COUNT(*) AS FISH_COUNT, 
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(COALESCE(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE ASC;